### ISSUE TITLE
Joining urls

### ISSUE THREAD

**Issue by codl** [TkTech/can_ada#6]
Any plans to add support for joining urls? For example if I have `https://example.com/foo/` and `../bar/baz.gif` I'd like to be able to combine them into `https://example.com/bar/baz.gif`. The official python ada binding supports this as `ada_url.join_url()`

**Comment by TkTech** [comment]
This is available now as of 1.2.0, which is currently getting deployed.

`url = URL("https://example.com/foo/") + "../bar/baz.gif"` results in a new URL object with the two Joined.

**Comment by TkTech** [comment]
... and, of course, pypi is down. Expect this to be available by tomorrow.
