### ISSUE TITLE
Type definitions not included in sdist or wheel

### ISSUE THREAD

**Issue by layday** [TkTech/can_ada#7]
The following two files are missing from both the sdist and the wheel:

* `py.typed`
* `can_ada.pyi`

**Comment by TkTech** [comment]
Weirdly more difficult then it should be to fix this! Old-style manifests no longer seem to work, including it in the pyproject.toml caused a bug in some versions of pip, and in switching fully over to poetry to just use the pyproject.toml approach I ran into poetry bugs with pure extensions (no Python code).

I will most likely fully switch over to poetry + pyproject.toml and will fix the upstream bug in poetry.

**Comment by layday** [comment]
You could try creating a stubs-only package if that's easier, renaming `can_ada.pyi` to `can_ada-stubs/__init__.pyi` - see https://peps.python.org/pep-0561/#stub-only-packages.

**Comment by TkTech** [comment]
Resolved with 1.3.0
