### ISSUE TITLE
[FYI] Now available from ArchLinux User Repository

### ISSUE THREAD

**Issue by kseistrup** [TkTech/can_ada#8]
[ This issue is informational only: No action is needed on your part, and you may close it at your discretion. ]

I reckoned you'd like to know that ArchLinux users can now install this directly from ArchLinux User Repository (AUR) as `python-can_ada-git`:

* https://aur.archlinux.org/packages/python-can_ada-git

It can be installed using an [AUR helper](https://wiki.archlinux.org/title/AUR_helpers), e.g. `yay`:

```sh
# Build the Python module from the latest commit, and
# install it along with the README and the LICENSE:
yay -S python-can_ada-git
```

:pray:

**Comment by TkTech** [comment]
Awesome! Took a quick look at the PKGBUILD and it looks good, not that I'm overly familiar with it.
